# Data path
#datadir: "/proj/uppstore2019111/nobackup/private/nbis4833/tst/bam/"
datadir: "/proj/uppstore2019111/private/01-Results/bwa/"


# Output paths
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: "/proj/uppstore2019111/nobackup/private/nbis4833/analysis/processing/ATAC-seq_pipeline/atacseq_proc_snakefile"

# annotation
blacklist: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/blacklist/ENCFF547MET.ens.bed"
mt: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/blacklist/mt.bed"

#gene and TSS annotation for heatmap plotting
allTSS: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/bed/refTSS_ALLcenterpoint.bed"
trxTSS: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/bed/refTSS_geneid.bed"
ens5gene: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/bed/ens_5gene.bed"
MGIgene: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/bed/MGI_gene.bed"

# genome size and fragment size
efGenomeSize: "2308125349"
extSize: "300"

