#working directory i.e. parent directory where the results are written
#workdir: "/proj/sllstore2017028/nobackup/nbis4067/results/data2018/april2018/"

# Data path
datadir: "/proj/uppstore2019111/nobackup/private/nbis4833/tst/bam/"


# Output paths
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: ""

