# Data path
datadir: "/proj/uppstore2019111/nobackup/private/nbis4833/tst/bam/"


# Output paths
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: "/proj/uppstore2019111/nobackup/private/nbis4833/tst/pipeline/ATAC-seq_pipeline/atacseq_proc_snakefile"

# annotation
blacklist: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/blacklist/ENCFF547MET.ens.bed"
mt: "/proj/uppstore2019111/nobackup/private/nbis4833/annotation/blacklist/mt.bed"

# genome size and fragment size
efGenomeSize: "2308125349"
extSize: "300"

